---
- hosts: localhost
  tasks:
    - include install-galaxy-roles.yaml

- hosts: others
  roles:
  - role : geerlingguy.java
    become: yes
    java_packages:
      - java-1.8.0-openjdk-devel
  - role: gantsign.maven
    become: yes  
 
- hosts: others
  tasks:
    - name: "install git cli"
      yum:
        name: git
        state: latest         
    
- hosts: others
  tasks:
    - name : "enable jenkins repository"
      become: yes
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name : "add jenkins repository"
      become: yes
      shell: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    - name : "install jenkins"
      become: yes
      yum:
        name: jenkins
        state: latest
    - name : "enable and start jenkins service"
      become: yes
      service:
        name: jenkins
        enabled: yes
        state: started
       
- hosts: others
  tasks:
    - name : "download kubectl"
      become: yes
      shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - name : "change permission of kubectl file"
      become: yes
      file: 
        path: ./kubectl
        mode: +x
    - name : "move kubectl to /usr/bin"
      become: yes
      shell: mv kubectl /usr/bin
    - name : "create /home/jenkins/.kube directory"
      become: yes
      file:
        path: /home/jenkins/.kube/
        state: directory    

      
- hosts: others
  roles:
  - role: geerlingguy.docker
    become: yes
    vars:
      docker_edition: 'ce'
      docker_users:
        - jenkins

- hosts: others
  tasks:
    - name: "add insecure nexus registry"
      become: yes
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
    - name: "restart docker"
      become: yes
      service:
        name: docker
        state: restarted 
 
- hosts: others
  tasks:
    - name: restart jenkins
      become: yes
      service:
        name: jenkins
        state: restarted